2025-04-08 15:11:17,496 - INFO - Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2025-04-08 15:11:17,496 - INFO - NumExpr defaulting to 8 threads.
wandb: Currently logged in as: rongite2022 (loongjk). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.19.9 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.5
wandb: Run data is saved locally in /home/jlong1/Downloads/Synthetic_Data_for_ZO/PromptZO/MeZO/large_models/wandb/run-20250408_151119-s1ho39i4
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run smart-firefly-39
wandb: ‚≠êÔ∏è View project at https://wandb.ai/loongjk/Synthetic_Data_for_ZO-PromptZO_MeZO_large_models
wandb: üöÄ View run at https://wandb.ai/loongjk/Synthetic_Data_for_ZO-PromptZO_MeZO_large_models/runs/s1ho39i4/workspace
2025-04-08 15:11:22,026 - INFO - We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
max_steps is given, it will override any value given in num_train_epochs
2025-04-08 15:11:32,462 - INFO - ***** Running training *****
2025-04-08 15:11:32,463 - INFO -   Num examples = 150
2025-04-08 15:11:32,463 - INFO -   Num Epochs = 2000
2025-04-08 15:11:32,463 - INFO -   Instantaneous batch size per device = 16
2025-04-08 15:11:32,463 - INFO -   Total train batch size (w. parallel, distributed & accumulation) = 16
2025-04-08 15:11:32,463 - INFO -   Gradient Accumulation steps = 1
2025-04-08 15:11:32,463 - INFO -   Total optimization steps = 20000
2025-04-08 15:11:32,464 - INFO -   Number of trainable parameters = 5636096
  0%|          | 0/20000 [00:00<?, ?it/s]You're using a PreTrainedTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
Traceback (most recent call last):
  File "/home/jlong1/Downloads/Synthetic_Data_for_ZO/PromptZO/MeZO/large_models/run.py", line 669, in <module>
    main()
  File "/home/jlong1/Downloads/Synthetic_Data_for_ZO/PromptZO/MeZO/large_models/run.py", line 631, in main
    framework.train(train_samples, dev_samples if dev_samples is not None else eval_samples, eval_samples)
  File "/home/jlong1/Downloads/Synthetic_Data_for_ZO/PromptZO/MeZO/large_models/run.py", line 566, in train
    self.trainer.train(resume_from_checkpoint=last_checkpoint)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/home/jlong1/Downloads/Synthetic_Data_for_ZO/PromptZO/MeZO/large_models/trainer.py", line 1089, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/jlong1/Downloads/Synthetic_Data_for_ZO/PromptZO/MeZO/large_models/trainer.py", line 529, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/jlong1/Downloads/Synthetic_Data_for_ZO/PromptZO/MeZO/large_models/trainer.py", line 593, in compute_loss
    outputs = model(**inputs)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jlong1/Downloads/Synthetic_Data_for_ZO/PromptZO/MeZO/large_models/utils.py", line 44, in forward_wrap_with_option_len
    outputs = self.original_forward(input_ids=input_ids, **kwargs)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1161, in forward
    logits = logits.float()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.75 GiB. GPU 0 has a total capacty of 47.41 GiB of which 321.56 MiB is free. Process 3362358 has 27.47 GiB memory in use. Including non-PyTorch memory, this process has 19.04 GiB memory in use. Of the allocated memory 18.50 GiB is allocated by PyTorch, and 240.74 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
wandb: - 0.006 MB of 0.025 MB uploadedwandb: üöÄ View run smart-firefly-39 at: https://wandb.ai/loongjk/Synthetic_Data_for_ZO-PromptZO_MeZO_large_models/runs/s1ho39i4/workspace
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250408_151119-s1ho39i4/logs
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
Exception in thread IntMsgThr:
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/threading.py", line 953, in run
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 268, in check_network_status
    self.run()
    self._loop_check_status(
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/threading.py", line 953, in run
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
    self._target(*self._args, **self._kwargs)
    local_handle = request()
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 300, in check_internal_messages
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 836, in deliver_network_status
    self._loop_check_status(
    return self._deliver_network_status(status)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 510, in _deliver_network_status
    local_handle = request()
    return self._deliver_record(record)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 844, in deliver_internal_messages
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 459, in _deliver_record
    return self._deliver_internal_messages(internal_message)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 516, in _deliver_internal_messages
    handle = mailbox._deliver_record(record, interface=self)
    return self._deliver_record(record)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 459, in _deliver_record
    interface._publish(record)
    handle = mailbox._deliver_record(record, interface=self)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    self._sock_client.send_record_publish(record)
    interface._publish(record)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self.send_server_request(server_req)
    self._sock_client.send_record_publish(record)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self._send_message(msg)
    self.send_server_request(server_req)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._sendall_with_error_handle(header + data)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    self._send_message(msg)
    sent = self._sock.send(data)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
BrokenPipeError: [Errno 32] Broken pipe
    self._sendall_with_error_handle(header + data)
  File "/home/jlong1/miniconda3/envs/mezo/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
